return {
	{
		"Mofiqul/dracula.nvim",
		name = "dracula",
		priority = 1000,
		lazy = false,
		opts = {
			colors = {
				bg = "#fbfaf8",
				fg = "#242126",
				selection = "#e5dfd8",
				comment = "#6f6872",
				red = "#8f003b",
				orange = "#7b4cc2",
				yellow = "#806200",
				green = "#167a3c",
				purple = "#b00048",
				cyan = "#006f8f",
				pink = "#c50047",
				bright_red = "#c7255a",
				bright_green = "#23864a",
				bright_yellow = "#8a6a00",
				bright_blue = "#256fb5",
				bright_magenta = "#8a4fc4",
				bright_cyan = "#007b98",
				bright_white = "#111214",
				menu = "#f1eeea",
				visual = "#e5dfd8",
				gutter_fg = "#8a838d",
				nontext = "#d7d0c8",
				white = "#242126",
				black = "#fbfaf8",
			},
			transparent_bg = false,
			italic_comment = true,
			overrides = function(colors)
				return {
					Normal = { fg = colors.fg, bg = colors.bg },
					NormalNC = { fg = colors.fg, bg = colors.bg },
					AlphaHeader = { fg = colors.purple },
					AlphaButtons = { fg = colors.purple },
					AlphaShortcut = { fg = colors.purple },
					AlphaFooter = { fg = colors.purple },
					DashboardHeader = { fg = colors.purple },
					DashboardCenter = { fg = colors.purple },
					DashboardShortCut = { fg = colors.purple },
					DashboardFooter = { fg = colors.purple },
					LineNr = { fg = colors.comment },
					CursorLineNr = { fg = colors.purple },
					CursorLine = { bg = "#f1eeea" },
					FloatBorder = { fg = "#d7d0c8", bg = "#f1eeea" },
					NormalFloat = { bg = "#f1eeea" },
					Keyword = { fg = colors.purple },
					Function = { fg = colors.cyan },
					Type = { fg = colors.green },
					["@function"] = { fg = colors.cyan },
					["@keyword"] = { fg = colors.purple },
					["@type"] = { fg = colors.green },
					["@string"] = { fg = colors.yellow },
					Directory = { fg = colors.purple },
					Search = { bg = "#e5dfd8", fg = colors.purple },
					IncSearch = { bg = colors.purple, fg = colors.bg },
					Visual = { bg = "#e5dfd8" },
					LspReferenceText = { bg = "#e5dfd8" },
					LspReferenceRead = { bg = "#e5dfd8" },
					LspReferenceWrite = { bg = "#e5dfd8" },
					TelescopeSelectionCaret = { fg = colors.purple },
					TelescopeSelection = { fg = colors.purple, bg = "#f1eeea" },
					TelescopePromptPrefix = { fg = colors.purple },
					TelescopeBorder = { fg = "#d7d0c8", bg = colors.bg },
					TelescopePromptNormal = { bg = "#f1eeea" },
					TelescopePromptBorder = { fg = "#d7d0c8", bg = "#f1eeea" },
					NeoTreeDirectoryIcon = { fg = colors.purple },
					NeoTreeDirectoryName = { fg = colors.purple },
					GitSignsAdd = { fg = colors.green },
					GitSignsChange = { fg = colors.cyan },
					GitSignsDelete = { fg = colors.pink },
					IndentBlanklineChar = { fg = colors.nontext },
					IndentBlanklineContextChar = { fg = colors.comment },
					StatusLine = { bg = colors.bg },
					TabLine = { bg = colors.bg },
					TabLineSel = { fg = colors.purple, bg = "#f1eeea" },
					NoiceCmdlineIcon = { fg = colors.purple },
					NoiceCmdlinePopupBorder = { fg = "#d7d0c8" },
					NoiceCmdlinePopup = { bg = "#f1eeea" },
				}
			end,
		},
	},
	{
		"LazyVim/LazyVim",
		opts = {
			colorscheme = "dracula",
		},
	},
	{
		"nvim-lualine/lualine.nvim",
		opts = function(_, opts)
			local colors = {
				bg = "#fbfaf8",
				elevated = "#f1eeea",
				fg = "#242126",
				ruby = "#b00048",
				border = "#d7d0c8",
				muted = "#6f6872",
				green = "#167a3c",
				pink = "#c50047",
				yellow = "#806200",
				cyan = "#006f8f",
				magenta = "#7b4cc2",
			}
			opts.options = opts.options or {}
			opts.options.theme = {
				normal = {
					a = { bg = colors.ruby, fg = colors.bg, gui = "bold" },
					b = { bg = colors.elevated, fg = colors.fg },
					c = { bg = colors.bg, fg = colors.fg },
				},
				insert = {
					a = { bg = colors.green, fg = colors.bg, gui = "bold" },
					b = { bg = colors.elevated, fg = colors.green },
					c = { bg = colors.bg, fg = colors.fg },
				},
				visual = {
					a = { bg = colors.magenta, fg = colors.bg, gui = "bold" },
					b = { bg = colors.elevated, fg = colors.magenta },
					c = { bg = colors.bg, fg = colors.fg },
				},
				replace = {
					a = { bg = colors.yellow, fg = colors.bg, gui = "bold" },
					b = { bg = colors.elevated, fg = colors.yellow },
					c = { bg = colors.bg, fg = colors.fg },
				},
				command = {
					a = { bg = colors.cyan, fg = colors.bg, gui = "bold" },
					b = { bg = colors.elevated, fg = colors.cyan },
					c = { bg = colors.bg, fg = colors.fg },
				},
				inactive = {
					a = { bg = colors.bg, fg = colors.muted },
					b = { bg = colors.bg, fg = colors.muted },
					c = { bg = colors.bg, fg = colors.muted },
				},
			}
		end,
	},
}
